cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_page, name='cart_page'),
    path("add/<int:product_id>/", views.cart_add, name='cart_add'),
    path("remove/<int:product_id>/", views.delete_cart, name='delete_cart'),
]

clothing/urls.py
from django.contrib import admin
from django.urls import path,  include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('payment/', include('payment.urls',namespace='payment')),
    path('order/', include("orders.urls", namespace='orders')),
    path("/cart/", include("cart.urls", namespace="cart")),
    path('admin/', admin.site.urls),
    path("", include("store.urls", namespace="store")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path("create/", views.order_page, name="order_page")
]

store/urls.py
from django.urls import path
from . import views

app_name = "store"

urlpatterns = [
    path("", views.store_page, name="store_page"),
    path("<slug:category_slug>/", views.store_page, name="store_page"),
    path("<slug:slug>/<int:detail_id>/",
         views.detail_page, name="detail_page"),
]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    updated = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from store.models import Product
from .cart import Cart
from .forms import CartForm


def cart_page(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartForm(
            initial={'quantity': item['quantity'], 'updated': True})
    return render(request, 'cart/cart.html', {'cart': cart})


@require_POST
def cart_add(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart = Cart(request)
    form = CartForm(request.POST)
    if form.is_valid():
        quantity = form.cleaned_data.get("quantity")
        updated = form.cleaned_data.get("updated")

        cart.add(product=product, quantity=quantity, updated_quantity=updated)

    return redirect("cart:cart_page")


@require_POST
def delete_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart = Cart(request)

    cart.remove(product=product)
    return redirect("cart:cart_page")

cart/templates/cart/cart.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block title %}cart{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<div class="box-element">
				<a class='btn btn-outline-info' href="{% url 'store:store_page' %}">&#x2190; Continue shopping</a>
			</div>
			<br>
			<br>
			<table class="table">
				{% with total=cart|length %}
				<tr>
					<th>
						<h4 class="text-primary">Total Items: <strong>{{ total }}</strong></h4>
					</th>
					<th>
						<h4 class="text-primary">Total items price: <strong>{{ cart.get_total_price }}</strong></h4>
					</th>
					<th>
						<a style="float:right; margin:5px;" class="btn btn-success"
							href="{% url 'orders:order_page' %}">Checkout</a>
					</th>
				</tr>
				{% endwith %}
			</table>
			<div class="box-element">
				<div class="cart-row">
					<div style="flex:2"></div>
					<div style="flex:2"><strong>Item</strong></div>
					<div style="flex:1"><strong>Price</strong></div>
					<div style="flex:1"><strong>Quantity</strong></div>
					<div style="flex:1"><strong>Remove</strong></div>
					<div style="flex:1"><strong>Total</strong></div>
				</div>
				{% for item in cart %}
				{% with product=item.product %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{ product.imageURL}}"></div>
					<div style="flex:2">
						<p>{{ product.name }}</p>
					</div>
					<div style="flex:1">
						<p>${{ item.price }}</p>
					</div>
					<div style="flex:1">
						<p class="quantity">{{ item.quantity }}</p>
						<div class="quantity">
							<form action="{% url 'cart:cart_add' product.id %}" method="POST">
								{{ item.update_quantity_form.quantity }}
								{{ item.update_quantity_form.updated }}
								{% csrf_token %}
								<hr>
								<button class="btn btn-primary btn-md my-0 p" type="submit">update</button>
							</form>
						</div>
					</div>
					<div style="flex:1">
						<form action="{% url 'cart:delete_cart' product.id %}" method="POST">
							<button class="btn btn-danger btn-md my-0 p" type="submit">remove</button>
							{% csrf_token %}
						</form>
					</div>
					<div style="flex:1">
						<p>{{ item.total_price }}</p>
					</div>
				</div>
				{% endwith %}
				{% endfor %}
			</div>
		</div>
	</div>
</div>
{% endblock %}